// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users_management.proto

package users_management

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRegistrationRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Dob                  string   `protobuf:"bytes,3,opt,name=dob,proto3" json:"dob,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Role                 []int32  `protobuf:"varint,6,rep,packed,name=role,proto3" json:"role,omitempty"`
	Password             string   `protobuf:"bytes,7,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegistrationRequest) Reset()         { *m = UserRegistrationRequest{} }
func (m *UserRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegistrationRequest) ProtoMessage()    {}
func (*UserRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2161d565771b06bd, []int{0}
}

func (m *UserRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegistrationRequest.Unmarshal(m, b)
}
func (m *UserRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *UserRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegistrationRequest.Merge(m, src)
}
func (m *UserRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegistrationRequest.Size(m)
}
func (m *UserRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegistrationRequest proto.InternalMessageInfo

func (m *UserRegistrationRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserRegistrationRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserRegistrationRequest) GetDob() string {
	if m != nil {
		return m.Dob
	}
	return ""
}

func (m *UserRegistrationRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserRegistrationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRegistrationRequest) GetRole() []int32 {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *UserRegistrationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserRegistrationResponse struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegistrationResponse) Reset()         { *m = UserRegistrationResponse{} }
func (m *UserRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*UserRegistrationResponse) ProtoMessage()    {}
func (*UserRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2161d565771b06bd, []int{1}
}

func (m *UserRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegistrationResponse.Unmarshal(m, b)
}
func (m *UserRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegistrationResponse.Marshal(b, m, deterministic)
}
func (m *UserRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegistrationResponse.Merge(m, src)
}
func (m *UserRegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_UserRegistrationResponse.Size(m)
}
func (m *UserRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegistrationResponse proto.InternalMessageInfo

func (m *UserRegistrationResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type UserLoginRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2161d565771b06bd, []int{2}
}

func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

type UserLoginResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResponse) Reset()         { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()    {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2161d565771b06bd, []int{3}
}

func (m *UserLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResponse.Unmarshal(m, b)
}
func (m *UserLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResponse.Marshal(b, m, deterministic)
}
func (m *UserLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResponse.Merge(m, src)
}
func (m *UserLoginResponse) XXX_Size() int {
	return xxx_messageInfo_UserLoginResponse.Size(m)
}
func (m *UserLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UserRegistrationRequest)(nil), "UserRegistrationRequest")
	proto.RegisterType((*UserRegistrationResponse)(nil), "UserRegistrationResponse")
	proto.RegisterType((*UserLoginRequest)(nil), "UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "UserLoginResponse")
}

func init() { proto.RegisterFile("users_management.proto", fileDescriptor_2161d565771b06bd) }

var fileDescriptor_2161d565771b06bd = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xcd, 0x4a, 0xf4, 0x40,
	0x10, 0xfc, 0xf2, 0xed, 0x8f, 0xa6, 0x15, 0x59, 0xdb, 0xbf, 0x71, 0xf1, 0x10, 0x72, 0xda, 0x53,
	0x0e, 0x0a, 0x3e, 0x80, 0x28, 0x7b, 0xd1, 0x45, 0x22, 0x9e, 0x65, 0xe2, 0xb6, 0x71, 0x20, 0xc9,
	0xc4, 0xe9, 0x89, 0x3e, 0xa5, 0x4f, 0xe2, 0x4b, 0xc8, 0x4c, 0xdc, 0x18, 0x90, 0xbd, 0xe8, 0xad,
	0xab, 0xaa, 0x53, 0x95, 0x6a, 0x06, 0x0e, 0x1b, 0x26, 0xc3, 0x0f, 0xa5, 0xac, 0x64, 0x4e, 0x25,
	0x55, 0x36, 0xa9, 0x8d, 0xb6, 0x3a, 0x7e, 0x0f, 0xe0, 0xe8, 0x9e, 0xc9, 0xa4, 0x94, 0x2b, 0xb6,
	0x46, 0x5a, 0xa5, 0xab, 0x94, 0x5e, 0x1a, 0x62, 0x8b, 0x27, 0x10, 0x3e, 0x29, 0xc3, 0x76, 0x21,
	0x4b, 0x12, 0x41, 0x14, 0xcc, 0xc2, 0xf4, 0x9b, 0xc0, 0x29, 0x6c, 0x16, 0xf2, 0x4b, 0xfc, 0xef,
	0xc5, 0x0e, 0xe3, 0x04, 0x06, 0x4b, 0x9d, 0x89, 0x81, 0xa7, 0xdd, 0x88, 0x11, 0x6c, 0xd5, 0xcf,
	0xba, 0xa2, 0x45, 0x53, 0x66, 0x64, 0xc4, 0xd0, 0x2b, 0x7d, 0x0a, 0xf7, 0x61, 0x44, 0xa5, 0x54,
	0x85, 0x18, 0x79, 0xad, 0x05, 0x88, 0x30, 0x34, 0xba, 0x20, 0x31, 0x8e, 0x06, 0xb3, 0x51, 0xea,
	0x67, 0x97, 0x7c, 0x2b, 0x99, 0xdf, 0xb4, 0x59, 0x8a, 0x8d, 0x36, 0x79, 0x85, 0xe3, 0x73, 0x10,
	0x3f, 0xeb, 0x70, 0xad, 0x2b, 0xf6, 0xdf, 0x39, 0xad, 0x57, 0xa7, 0xc3, 0x31, 0xc2, 0xc4, 0xcd,
	0xd7, 0x3a, 0x57, 0xab, 0xfe, 0xf1, 0x1e, 0xec, 0xf6, 0xb8, 0xd6, 0xe4, 0xf4, 0x23, 0x80, 0x03,
	0xc7, 0xde, 0x74, 0x97, 0xbc, 0x23, 0xf3, 0xaa, 0x1e, 0x09, 0xaf, 0x60, 0xbb, 0x8d, 0x25, 0xe3,
	0x16, 0x50, 0x24, 0x6b, 0x0e, 0x3b, 0x3d, 0x4e, 0xd6, 0xfd, 0x63, 0xfc, 0x0f, 0x2f, 0x20, 0xf4,
	0x89, 0x7f, 0xf1, 0x98, 0xc3, 0xce, 0x9c, 0xac, 0x5b, 0xb8, 0x24, 0x2b, 0x55, 0xc1, 0xbf, 0x34,
	0xca, 0xc6, 0xfe, 0x95, 0x9c, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff, 0x05, 0xc4, 0x6b, 0xf5, 0x3f,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserManagementServiceClient is the client API for UserManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserManagementServiceClient interface {
	RegisterUser(ctx context.Context, in *UserRegistrationRequest, opts ...grpc.CallOption) (*UserRegistrationResponse, error)
	LoginUser(ctx context.Context, in *UserRegistrationRequest, opts ...grpc.CallOption) (*UserRegistrationResponse, error)
	GetUserDetails(ctx context.Context, in *UserRegistrationRequest, opts ...grpc.CallOption) (*UserRegistrationResponse, error)
}

type userManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserManagementServiceClient(cc grpc.ClientConnInterface) UserManagementServiceClient {
	return &userManagementServiceClient{cc}
}

func (c *userManagementServiceClient) RegisterUser(ctx context.Context, in *UserRegistrationRequest, opts ...grpc.CallOption) (*UserRegistrationResponse, error) {
	out := new(UserRegistrationResponse)
	err := c.cc.Invoke(ctx, "/UserManagementService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementServiceClient) LoginUser(ctx context.Context, in *UserRegistrationRequest, opts ...grpc.CallOption) (*UserRegistrationResponse, error) {
	out := new(UserRegistrationResponse)
	err := c.cc.Invoke(ctx, "/UserManagementService/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementServiceClient) GetUserDetails(ctx context.Context, in *UserRegistrationRequest, opts ...grpc.CallOption) (*UserRegistrationResponse, error) {
	out := new(UserRegistrationResponse)
	err := c.cc.Invoke(ctx, "/UserManagementService/GetUserDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserManagementServiceServer is the server API for UserManagementService service.
type UserManagementServiceServer interface {
	RegisterUser(context.Context, *UserRegistrationRequest) (*UserRegistrationResponse, error)
	LoginUser(context.Context, *UserRegistrationRequest) (*UserRegistrationResponse, error)
	GetUserDetails(context.Context, *UserRegistrationRequest) (*UserRegistrationResponse, error)
}

// UnimplementedUserManagementServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserManagementServiceServer struct {
}

func (*UnimplementedUserManagementServiceServer) RegisterUser(ctx context.Context, req *UserRegistrationRequest) (*UserRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (*UnimplementedUserManagementServiceServer) LoginUser(ctx context.Context, req *UserRegistrationRequest) (*UserRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (*UnimplementedUserManagementServiceServer) GetUserDetails(ctx context.Context, req *UserRegistrationRequest) (*UserRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDetails not implemented")
}

func RegisterUserManagementServiceServer(s *grpc.Server, srv UserManagementServiceServer) {
	s.RegisterService(&_UserManagementService_serviceDesc, srv)
}

func _UserManagementService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserManagementService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).RegisterUser(ctx, req.(*UserRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserManagementService/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).LoginUser(ctx, req.(*UserRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementService_GetUserDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).GetUserDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserManagementService/GetUserDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).GetUserDetails(ctx, req.(*UserRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserManagementService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserManagementService",
	HandlerType: (*UserManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _UserManagementService_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _UserManagementService_LoginUser_Handler,
		},
		{
			MethodName: "GetUserDetails",
			Handler:    _UserManagementService_GetUserDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users_management.proto",
}
